#!/bin/bash

tmpdir=$(mktemp -d)

for i in *.tex; do
  [[ -f "$i" ]] || continue 
  latex -output-directory="$tmpdir" "$i";
  dvipdfm -o "$tmpdir/${i%.tex}.pdf" "$tmpdir/${i%.tex}.dvi";
  zathura "$tmpdir/${i%.tex}.pdf";
done;

rm -rf "$tmpdir";
